# Generated by Django 3.1.5 on 2021-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='yandex_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
